---
2018-04-08: config/thresholds/2018-04-08.yml
2019-04-08: config/thresholds/2019-04-08.yml
2020-04-06: config/thresholds/2020-04-06.yml
2021-01-28: config/thresholds/2021-01-28.yml
2021-04-12: config/thresholds/2021-04-12.yml
2022-04-11: config/thresholds/2022-04-11.yml
2023-04-10: config/thresholds/2023-04-10.yml
# MTR is under development, so marked 'test_only'.
# MTR implementation date is just a placeholder for now.
2026-04-01: config/thresholds/mtr-2026.yml
